import httpx
import pytest
import respx

from app.core.config import Settings
from app.services.gitlab_mcp_client import (
    GitLabAuthenticationError,
    GitLabMCPClient,
    GitLabNotFoundError,
    GitLabRateLimitError,
)


def make_settings(dry_run: bool = True) -> Settings:
    return Settings(
        _env_file=None,
        gitlab_base_url="https://gitlab.example.com",
        gitlab_personal_access_token="test-token",
        gitlab_webhook_secret="webhook-secret",
        gitlab_project_id=123,
        dry_run=dry_run,
    )


@pytest.mark.asyncio
@respx.mock
async def test_list_pipeline_jobs_and_filter_failed_jobs() -> None:
    route = respx.get(
        "https://gitlab.example.com/api/v4/projects/123/pipelines/456/jobs"
    ).mock(
        return_value=httpx.Response(
            200,
            json=[
                {"id": 1, "status": "success"},
                {"id": 2, "status": "failed"},
            ],
        )
    )

    client = GitLabMCPClient(settings=make_settings())

    jobs = await client.list_pipeline_jobs(123, 456)
    failed_jobs = await client.get_failed_jobs(123, 456)

    assert route.called
    assert len(jobs) == 2
    assert failed_jobs == [{"id": 2, "status": "failed"}]


@pytest.mark.asyncio
@respx.mock
async def test_read_job_trace_returns_text() -> None:
    respx.get("https://gitlab.example.com/api/v4/projects/123/jobs/99/trace").mock(
        return_value=httpx.Response(200, text="Traceback: SyntaxError")
    )
    client = GitLabMCPClient(settings=make_settings())

    trace = await client.read_job_trace(123, 99)

    assert trace == "Traceback: SyntaxError"


@pytest.mark.asyncio
@respx.mock
async def test_get_file_content_encodes_file_path() -> None:
    route = respx.get(
        "https://gitlab.example.com/api/v4/projects/123/repository/files/src%2Fapp.py/raw"
    ).mock(return_value=httpx.Response(200, text="print('ok')\n"))
    client = GitLabMCPClient(settings=make_settings())

    content = await client.get_file_content(123, "src/app.py", "main")

    assert route.called
    assert content == "print('ok')\n"


@pytest.mark.asyncio
async def test_dry_run_write_operations_do_not_call_gitlab() -> None:
    client = GitLabMCPClient(settings=make_settings(dry_run=True))

    branch = await client.create_branch(123, "syntaxsentinel/fix-pipeline-456", "main")
    commit = await client.commit_file_changes(
        123,
        "syntaxsentinel/fix-pipeline-456",
        "Fix pipeline failure",
        [{"action": "update", "file_path": "app.py", "content": "print('ok')"}],
    )
    merge_request = await client.create_merge_request(
        123,
        "syntaxsentinel/fix-pipeline-456",
        "main",
        "Fix pipeline failure",
        "Generated by SyntaxSentinel.",
    )
    note = await client.add_merge_request_note(123, 1, "Safety note")

    assert branch["dry_run"] is True
    assert commit["dry_run"] is True
    assert commit["action_count"] == 1
    assert merge_request["dry_run"] is True
    assert note["dry_run"] is True


@pytest.mark.asyncio
@respx.mock
async def test_create_branch_calls_gitlab_when_not_dry_run() -> None:
    route = respx.post(
        "https://gitlab.example.com/api/v4/projects/123/repository/branches"
    ).mock(return_value=httpx.Response(201, json={"name": "fix", "ref": "main"}))
    client = GitLabMCPClient(settings=make_settings(dry_run=False))

    response = await client.create_branch(123, "fix", "main")

    assert route.called
    assert response == {"name": "fix", "ref": "main"}


@pytest.mark.asyncio
@respx.mock
async def test_get_project_returns_project_payload() -> None:
    respx.get("https://gitlab.example.com/api/v4/projects/123").mock(
        return_value=httpx.Response(200, json={"id": 123, "path": "demo"})
    )
    client = GitLabMCPClient(settings=make_settings())

    response = await client.get_project(123)

    assert response["id"] == 123


@pytest.mark.asyncio
@pytest.mark.parametrize(
    ("status_code", "exception_type"),
    [
        (401, GitLabAuthenticationError),
        (404, GitLabNotFoundError),
        (429, GitLabRateLimitError),
    ],
)
@respx.mock
async def test_gitlab_error_mapping(status_code: int, exception_type: type[Exception]) -> None:
    respx.get("https://gitlab.example.com/api/v4/projects/123").mock(
        return_value=httpx.Response(status_code, json={"message": "error"})
    )
    client = GitLabMCPClient(settings=make_settings())

    with pytest.raises(exception_type):
        await client.get_project(123)


@pytest.mark.asyncio
@respx.mock
async def test_retries_server_errors() -> None:
    route = respx.get("https://gitlab.example.com/api/v4/projects/123").mock(
        side_effect=[
            httpx.Response(500, json={"message": "temporary"}),
            httpx.Response(200, json={"id": 123}),
        ]
    )
    client = GitLabMCPClient(settings=make_settings(), max_retries=1)

    response = await client.get_project(123)

    assert route.call_count == 2
    assert response == {"id": 123}
